services: 
  pc:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - "./gp_env/:/home/mmr/gp_env/:rw"
    command: ["/bin/bash", "-c", "chmod +x /home/mmr/gp_env/run_global.sh && /home/mmr/gp_env/run_global.sh"]